name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required packages
        run: sudo apt-get update
      - name: Install dotfiles
        run: |
          chmod u+x .bin/install.sh
          .bin/install.sh
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -e SC1091
        with:
          scandir: './bin'
